# This is a generated file. Not intended for manual editing.
services:
  filestoringservice:
    build:
      context: "C:\\Users\\ponom\\RiderProjects\\Big_HW\\Big_HW_2_Ponomarev\\FileStoringService"
      dockerfile: "Dockerfile"
      target: "build"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "filestoringservice:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "C:\\Users\\ponom\\RiderProjects\\Big_HW\\Big_HW_2_Ponomarev\\FileStoringService:/app:rw"
    - "C:\\Users\\ponom\\RiderProjects\\Big_HW\\Big_HW_2_Ponomarev:/src:rw"
    - "C:\\Users\\ponom\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\ponom\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.4\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\ponom\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\ponom\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_5_21_18_30_40:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
