version: '3.9'

services:
  ordersdb:
    image: postgres:15
    container_name: ordersdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - orders_pgdata:/var/lib/postgresql/data
    networks:
      - shopnet

  paymentsdb:
    image: postgres:15
    container_name: paymentsdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
    ports:
      - "5433:5432"
    volumes:
      - payments_pgdata:/var/lib/postgresql/data
    networks:
      - shopnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - shopnet
  
  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: apigateway
    ports:
      - "8000:8080"
    depends_on:
      - ordersservice1
      - ordersservice2
      - paymentsservice
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - shopnet

  ordersservice1:
    build:
      context: .
      dockerfile: OrdersService/Dockerfile
    container_name: ordersservice1
    depends_on:
      - ordersdb
      - rabbitmq
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__OrdersDb: "Host=ordersdb;Port=5432;Database=orders_db;Username=postgres;Password=postgres"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
    networks:
      - shopnet

  ordersservice2:
    build:
      context: .
      dockerfile: OrdersService/Dockerfile
    container_name: ordersservice2
    depends_on:
      - ordersdb
      - rabbitmq
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__OrdersDb: "Host=ordersdb;Port=5432;Database=orders_db;Username=postgres;Password=postgres"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
    networks:
      - shopnet

  paymentsservice:
    build:
      context: .
      dockerfile: PaymentsService/Dockerfile
    container_name: paymentsservice
    ports:
      - "8081:8080"
    depends_on:
      - paymentsdb
      - rabbitmq
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PaymentsDb: "Host=paymentsdb;Port=5432;Database=payments_db;Username=postgres;Password=postgres"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
    networks:
      - shopnet

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: frontend
    ports:
      - "8082:80"
    depends_on:
      - apigateway
    networks:
      - shopnet

volumes:
  orders_pgdata:
  payments_pgdata:

networks:
  shopnet: